dev.database.KeyWord={
	baoliu:",ABSOLUTE,OVERLAPS,ACTION,PAD,ADA,PARTIAL,EXTERNAL,PASCAL,EXTRACT,POSITION,ALLOCATE,FALSE,PREPARE,FIRST,PRESERVE,FLOAT,ARE,PRIOR,PRIVILEGES,FORTRAN,ASSERTION,FOUND,AT,REAL,AVG,GET,GLOBAL,RELATIVE,GO,BIT,BIT_LENGTH,BOTH,ROWS,HOUR,CASCADED,SCROLL,IMMEDIATE,SECOND,CAST,SECTION,CATALOG,INCLUDE,CHAR,SESSION,CHAR_LENGTH,INDICATOR,CHARACTER,INITIALLY,CHARACTER_LENGTH,SIZE,INPUT,SMALLINT,INSENSITIVE,SPACE,INT,SQL,COLLATION,INTEGER,SQLCA,SQLCODE,INTERVAL,SQLERROR,CONNECT,SQLSTATE,CONNECTION,SQLWARNING,ISOLATION,SUBSTRING,CONSTRAINTS,SUM,LANGUAGE,CORRESPONDING,LAST,TEMPORARY,COUNT,LEADING,TIME,LEVEL,TIMESTAMP,TIMEZONE_HOUR,LOCAL,TIMEZONE_MINUTE,LOWER,MATCH,TRAILING,MAX,MIN,TRANSLATE,DATE,MINUTE,TRANSLATION,DAY,MODULE,TRIM,MONTH,TRUE,DEC,NAMES,DECIMAL,NATURAL,UNKNOWN,NCHAR,DEFERRABLE,NEXT,UPPER,DEFERRED,NO,USAGE,NONE,USING,DESCRIBE,DESCRIPTOR,DIAGNOSTICS,NUMERIC,VARCHAR,DISCONNECT,OCTET_LENGTH,DOMAIN,ONLY,WHENEVER,WORK,END-EXEC,WRITE,YEAR,OUTPUT,ZONE,EXCEPTION,",
	odbc:",FREE,ADMIN,GENERAL,AFTER,READS,AGGREGATE,ALIAS,RECURSIVE,GROUPING,REF,HOST,REFERENCING,ARRAY,IGNORE,RESULT,RETURNS,BEFORE,ROLE,BINARY,INITIALIZE,ROLLUP,ROUTINE,BLOB,INOUT,ROW,BOOLEAN,SAVEPOINT,BREADTH,CALL,SCOPE,SEARCH,ITERATE,LARGE,SEQUENCE,CLASS,LATERAL,SETS,CLOB,LESS,COMPLETION,LIMIT,SPECIFIC,SPECIFICTYPE,LOCALTIME,CONSTRUCTOR,LOCALTIMESTAMP,SQLEXCEPTION,LOCATOR,CUBE,MAP,CURRENT_PATH,START,CURRENT_ROLE,CYCLE,MODIFIES,STATEMENT,MODIFY,STATIC,STRUCTURE,TERMINATE,THAN,NCLOB,DEPTH,NEW,DEREF,DESTROY,TREAT,DESTRUCTOR,OBJECT,DETERMINISTIC,OLD,UNDER,DICTIONARY,OPERATION,UNNEST,ORDINALITY,OUT,DYNAMIC,EACH,PARAMETER,VARIABLE,EQUALS,PARAMETERS,EVERY,WITHOUT,PATH,POSTFIX,FLASE,PREFIX,PREORDER,",
	yuliu:",ADD,EXCEPT,PERCENT,ALL,EXEC,ACS,PLAN,ALTER,EXECUTE,PRECISION,AND,EXISTS,PRIMARY,ANY,EXIT,PRINT,AS,FETCH,PROC,ASC,FILE,PROCEDURE,AUTHORIZATION,FILLFACTOR,PUBLIC,BACKUP,FOR,RAISERROR,BEGIN,FOREIGN,READ,BETWEEN,FREETEXT,READTEXT,BREAK,FREETEXTTABLE,RECONFIGURE,BROWSE,FROM,REFERENCES,BULK,FULL,REPLICATION,BY,FUNCTION,RESTORE,CASCADE,GOTO,RESTRICT,CASE,GRANT,RETURN,CHECK,GROUP,REVOKE,CHECKPOINT,HAVING,RIGHT,CLOSE,HOLDLOCK,ROLLBACK,CLUSTERED,IDENTITY,ROWCOUNT,COALESCE,IDENTITY_INSERT,ROWGUIDCOL,COLLATE,IDENTITYCOL,RULE,COLUMN,IF,SAVE,COMMIT,IN,SCHEMA,COMPUTE,INDEX,SELECT,CONSTRAINT,INNER,SESSION_USER,CONTAINS,INSERT,SET,CONTAINSTABLE,INTERSECT,SETUSER,CONTINUE,INTO,SHUTDOWN,CONVERT,IS,SOME,CREATE,JOIN,STATISTICS,CROSS,KEY,SYSTEM_USER,CURRENT,KILL,TABLE,CURRENT_DATE,LEFT,TEXTSIZE,CURRENT_TIME,LIKE,THEN,CURRENT_TIMESTAMP,LINENO,TO,CURRENT_USER,LOAD,TOP,CURSOR,NATIONAL,TRAN,DATABASE,NOCHECK,TRANSACTION,DBCC,NONCLUSTERED,TRIGGER,DEALLOCATE,NOT,TRUNCATE,DECLARE,NULL,TSEQUAL,DEFAULT,NULLIF,UNION,DELETE,OF,UNIQUE,DENY,OFF,UPDATE,DESC,OFFSETS,UPDATETEXT,DISK,ON,USE,DISTINCT,OPEN,USER,DISTRIBUTED,OPENDATASOURCE,VALUES,DOUBLE,OPENQUERY,VARYING,DROP,OPENROWSET,VIEW,DUMMY,OPENXML,WAITFOR,DUMP,OPTION,WHEN,ELSE,OR,WHERE,END,ORDER,WHILE,ERRLVL,OUTER,WITH,ESCAPE,OVER,WRITETEXT,DUAL,ACCESS,CHAR_BASE,COLLECT,COMPRESS,IDENTIFIED,INCREMENT,JAVA,LOCK,MAXEXTENTS,MLSLABEL,NEXTVAL,NUMBER_BASE,OPERATOR,ORGANIZATION,PARTITION,POSITIVEN,RANGE,AUDIT,CURRVAL,EXCLUSIVE,EXTENDS,LONG,MOD,NOAUDIT,NOWAIT,OCIROWID,ONLINE,OTHERS,PCTFREE,PRAGMA,RAW,AUTHID,COMMENT,CONSTANT,ELSIF,HEAP,INTERFACE,LOOP,MINUS,MODE,NATURALN,NOCOMPRESS,OPAQUE,PLS_INTEGER,BODY,CLUSTER,DO,FORALL,INITIAL,LIMITED,NOCOPY,NUMBER,OFFLINE,PACKAGE,POSITIVE,PRIVATE,RAISE,RECORD,ROWNUM,SHARE,STDDEV,SYNONYM,VALIDATE,VARIANCE,RELEASE,REVERSE,ROWTYPE,SEPERATE,SUBTYPE,SYSDATE,RENAME,ROWID,SQLERRM,SUCCESSFUL,UID,RESOURCE,ROWLABEL,VARCHAR2,",
	xitong:",PARENT_ID,EXPORT_ITEM,EXPORT_TAB,EXPORT_DATA,DATA_ID,RA,OBJECT_ID,",
	getKeyWordMsg:function(pname){
		var msg="";
		if(pname){
			pname=","+pname.toUpperCase()+",";
			if(this.baoliu.indexOf(pname)!=-1){
				msg='保留'.loc();
			}else if(this.odbc.indexOf(pname)!=-1){
				msg="odbc";
			}else if(this.yuliu.indexOf(pname)!=-1){
				msg='预留'.loc();
			}else if(this.xitong.indexOf(pname)!=-1){
				msg='系统'.loc();
			}
		}
		return msg;
	}

}