module.exports = {
  name: '积聚创新',
  prefix: 'antdAdmin',
  footerText: 'Cunovs © 2017 积聚创新',
  logo: 'https://t.alipayobjects.com/images/T1QUBfXo4fXXXXXXXX.png',
  iconFontUrl: '//at.alicdn.com/t/font_c4y7asse3q1cq5mi.js',
  // baseURL: '',
  baseURL: 'http://192.168.0.66:8000/api/v1',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://localhost:7001', 'http://192.168.1.110:8000'],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  ajaxTimeout: 5000,
  notRedirectSign: '_not_redirect_',
  api: {
    userLogin: '/newlogin/login.jjs',
    userQuery: '/newlogin/_query.jjs',
    userLogout: '/newlogin/layout.jjs',
/*  userLogin: '/user/login',
    userQuery:'/user/',
    userLogout: '/user/logout',*/
    userInfo: '/userInfo',
    users: '/users',
    user: '/user/:id',
    dashboard: '/newlogin/_menus.jjs',
    // dashboard: '/dashboard',
  },
}
